apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: img-res
  namespace: default
spec:
  template:
    spec:
      containerConcurrency: 1000
      containers:
        - image: kind.local/server-img-res:1.1.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8081
          resources:
            requests:
              cpu: 100m
              memory: 256M
            limits:
              cpu: 200m
              memory: 512M
    metadata:
      annotations:
        autoscaling.knative.dev/target: "1000"
        autoscaling.knative.dev/scale-to-zero-pod-retention-period: "1h"