apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: ml-train
  namespace: default
spec:
  template:
    spec:
      containerConcurrency: 1000
      containers:
        - image: kind.local/server-ml-train:1.1.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8081
          resources:
            requests:
              cpu: 250m
              memory: 512M
            limits:
              cpu: 500m
    metadata:
      annotations:
        autoscaling.knative.dev/target: "1000"
        autoscaling.knative.dev/scale-to-zero-pod-retention-period: "1h"